config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'costs#index'

  resources :users, only: [] do 
    resources :costs
  end

  

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :costs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #make visitors login before using
  before_action :authenticate_user!
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
before_action :find_user

	def find_user
		@user = current_user
	end

	def index
		@costs = @user.costs
	end

	def show
		@cost = @user.costs.find params[:id]
	end

	def new
		@cost = Cost.new
	end

	def create
		@cost = @user.costs.build(cost_params)
		@cost.user = current_user

		if @cost.save
			redirect_to [@user, @cost]
		else
			render 'new'
		end
	end

	def edit
		@cost = @user.costs.find(params[:id])
	end

	def update
		@cost = @user.costs.find params[:id]

		if @cost.update(cost_params)
			redirect_to [@user, @cost]
		else
			render 'edit'
		end
	end

	def destroy
		@cost = @user.costs.find params[:id]
		@cost.destroy

		redirect_to user_costs_path(@user)
	end

private
	def cost_params
		params.require(:cost).permit(:name, :amount, :date, :paid_for, :paid_to)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costs/_form.html.erb
<%= form_for @cost, url: user_costs_path do |f| %>

	<% if @cost.errors.any? %>
		<div>
			<h2>
				<%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being added:
			</h2>
			<ul>
				<% @cost.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label "Amount (R)" %><br>
		<%= f.text_field :amount %>
	</p>

	<p>
		<%= f.label :date %><br>
		<%= f.text_field :date %><br>
	</p>

	<p>
		<%= f.label "Where did you spend?" %><br>
		<%= f.text_field :paid_to %><br>
	</p>

	<p>
		<%= f.label "What did you spend on?" %><br>
		<%= f.text_field :paid_for %><br>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/costs/edit.html.erb
<h1>Edit cost</h1>

<%= render 'form' %>

<% link_to 'Back', user_costs_path(@user) %>

app/views/costs/index.html.erb
<h1>Costs:</h1>

<ul>
	<% @costs.each do |cost| %>
		<li>
			<strong><%= link_to cost.paid_for, user_cost_path(@user, cost) %></strong> |
			<%= link_to "Edit", edit_user_cost_path(@user, cost) %> |
			<%= link_to "Delete", user_cost_path(@user, cost), method: :delete, data: { confirm: "Are you sure you want to delete this cost?" } %>
		</li>
	<% end %>
</ul>

<%= link_to "New Cost", new_user_cost_path(@user) %>

app/views/costs/new.html.erb
<h1>Add Cost</h1>

<%= render 'form' %>
<%= link_to 'Back', user_costs_path(@user) %>

app/views/costs/show.html.erb
<p>
	<strong>Cost:</strong>
	<%= @cost.amount %>
</p>

<p>
	<strong>Date:</strong>
	<%= @cost.date %>
</p>

<p>
	<strong>Paid To:</strong>
	<%= @cost.paid_to %>
</p>

<p>
	<strong>Paid For:</strong>
	<%= @cost.paid_for %>
</p>

<%= link_to 'Edit', edit_user_cost_path(@user, @cost) %> |
<%= link_to 'Back', user_costs_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<p class="navbar-text pull-right" >
<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	<%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
</p>

<head>
  <title>BruBudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>